### ISSUE TITLE
last tab generates blank line

### ISSUE THREAD

**Issue by CipherCloak** [ptournet/obsidian-html-tabs#4]
Hi @ptournet , thank you so much for the plugin!!!

Could you please check the following issue?

**Obsidian version:**  1.4.16 Community (appImage & .exe)
**OS:** Linux Mint & Windows 10
**Plugin version**: 1.1.0
**Problem**: The last TAB generates an empty line (refer to the following images)

![image](https://github.com/ptournet/obsidian-html-tabs/assets/3332674/8df35c3a-215e-4645-bad1-bfc6b3e68089)
_[ the last tab generates an empty line ]_

![image](https://github.com/ptournet/obsidian-html-tabs/assets/3332674/06183e8f-bed8-4332-89ed-2258a6f39bc2)
_[ the code I'm using to generate 2 tabs ]_

---

![image](https://github.com/ptournet/obsidian-html-tabs/assets/3332674/ca75a09f-754e-4370-b94b-5c2d37f7b1cc)
_[ the last tab generates an empty line ]_

![image](https://github.com/ptournet/obsidian-html-tabs/assets/3332674/74e77490-3e2f-47a9-b168-0a13db295da4)
_[ the code I'm using to generate 3 tabs ]_

**Comment by marchank0** [comment]
Obsidian 1.4.16
Plugin 1.1.0

Have this issue on iPad/iPhone/Mac
Obsidian generates an empty code block after latest tab  
Desktop version on Mac throws an exception in console like:

```JS
app.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'frontmatter')
    at e.onCacheChanged (app.js:1:2489253)
    at e.tryTrigger (app.js:1:695499)
    at e.trigger (app.js:1:695432)
    at t.trigger (app.js:1:1800309)
    at rebuildCurrentPageCache (plugin:html-tabs:175:22)
    at updateCache (plugin:html-tabs:169:3)
    at HTMLTabsPlugin.renderTabs (plugin:html-tabs:3446:5)
    at eval (plugin:html-tabs:3426:99)
    at app.js:1:1160121
    at t.postProcess (app.js:1:1230606)
    at t.postProcess (app.js:1:1229434)
    at h (app.js:1:1147622)
    at e.onRender (app.js:1:1147882)
```

**Comment by breakid** [comment]
I think the pull request I just submitted (#10) might coincidentally fix this. I still get the `TypeError` message, but I don't get the extra code block on the last tab.
